# Generated by Django 4.2.30 on 2026-09-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='job',
            name='ai_analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
