# Generated by Django 4.2.30 on 2026-09-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='match_source',
            field=models.CharField(choices=[('ai', 'AI'), ('local', 'Local')], default='local', max_length=10),
        ),
    ]
