# Generated by Django 4.2.30 on 2026-09-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
